name: tunnel
fragment_size: 100
device: CUDA:0
engine: tensor
multiprocessing: false
path_dataset: /home/brianzx/16833/project/data/tunnel/inspection/
# path_dataset: /home/brianzx/16833/project/data/tunnel/inspection_1/
# path_dataset: /home/brianzx/16833/project/data/tunnel/inspection_2/
# path_dataset: /home/brianzx/16833/project/data/tunnel/inspection_3/
# path_dataset: /home/brianzx/16833/project/data/tunnel/inspection_4/
# path_dataset: /home/brianzx/16833/project/data/tunnel/inspection_5/
depth_folder: depth
color_folder: color
path_intrinsic: /home/brianzx/16833/project/configs/intrinsics_depth_tunnel.json
path_color_intrinsic: /home/brianzx/16833/project/configs/intrinsics_color_tunnel.json
depth_min: 0.1
depth_max: 5.0
depth_scale: 2500.0
odometry_method: hybrid
odometry_loop_interval: 10
odometry_loop_weight: 0.1
odometry_distance_thr: 0.07
icp_method: colored
icp_voxelsize: 0.05
icp_distance_thr: 0.07
global_registration_method: ransac
registration_loop_weight: 0.1
integration_mode: color
voxel_size: 0.01
trunc_voxel_multiplier: 8.0
block_count: 40000
est_point_count: 8000000
surface_weight_thr: 3.0