dataset: 'scannet'
sync_method: loose
coarse: True
verbose: True
meshing:
  resolution: 256
tracking:
  vis_freq: 30
  vis_inside_freq: 30
  ignore_edge_W: 20
  ignore_edge_H: 20
  seperate_LR: False
  gt_camera: False
  const_speed_assumption: True
  lr: 0.0005      
  pixels: 1000
  iters: 30
mapping:
  every_frame: 10
  vis_freq: 30
  vis_inside_freq: 30
  mesh_freq: 30
  ckpt_freq: 30
  keyframe_every: 50
  mapping_window_size: 10
  pixels: 1000
  iters_first: 400
  iters: 10
  bound: [[4, 12],[-3,-2],[0, 3]]
  marching_cubes_bound: [[4, 12],[-3,-2],[0, 3]]
cam: 
  H: 480 
  W: 640
  fx: 386.22674560546875
  fy: 386.22674560546875
  cx: 317.3930969238281
  cy: 239.78431701660156
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 10
data:
  input_folder: Datasets/Demo
  output: output/new